### PR TITLE
[jpn] Adds Japanese .phones file and updated TSV files

### LINKED ISSUE #230: [jpn] Create .phones list for Japanese
As captioned.

### PR DESCRIPTION
**Pull request by ajmalanoski**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

Closes #230

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM. Hiragana phonemic was weirdly short before this, huh. Probably a human error (on my part?)

**Comment by kylebgorman** [comment]
One of the tests is failing:

```
test_language_data_matches_summary - tests.test_data.test_summary
AssertionError: jpn_hira_phonemic.tsv in data/tsv but not in data/languages_summary.tsv
```

I guess the first thing to do is rerun the `postprocess` and `generate_summary.py` scripts and recommit/repush?

**Comment by ajmalanoski** [comment]
Does `scrape.py` delete files with less than 100 entries? When I ran `./scrape.py && postprocess && generate_summary.py`, there were only 98 entries for `jpn_hira_phonemic.tsv`, so that might be what happened. I also found `jpn_hira_phonemic.tsv` in my trash, but I wasn't sure if the program did that, or if I had accidentally deleted it.

**Comment by kylebgorman** [comment]
It does, and that's the intended behavior.

**Comment by ajmalanoski** [comment]
Ah, okay, then that would explain the discrepancy. Do you want me to commit the deletion, then?

**Comment by kylebgorman** [comment]
Please do, thanks.

**Comment by ajmalanoski** [comment]
Alright, it's taken care of.

**Comment by kylebgorman** [comment]
Checks passing, about to merge. Thanks!

**Pull request merged**
