### PR TITLE
[lcp] Configuration for Western lawa.

### PR DESCRIPTION
**Pull request by agutkin**
There are a few pronunciations with dashes in them, so we miss the target.

- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Could you run `black -l79` on `wikipron/languagecodes.py`?

**Comment by agutkin** [comment]
It was fine in my version. But not in your merge.

**Comment by agutkin** [comment]
Aha.. I see. I was running black on the languagecodes

**Comment by agutkin** [comment]
It now barfs about `wikipron/languagecodes.py`

**Pull request merged**
