### PR TITLE
[hbs] Fixes Serbo-Croatian phoneme lists. Re-scrapes data.

### PR DESCRIPTION
**Pull request by ajmalanoski**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Some changes to Hindi got mixed into this. Perhaps you want to roll those back and save for another PR. But other than that, LGTM.

**Review by kylebgorman — APPROVED** [review]

**Comment by ajmalanoski** [comment]
That's odd, I don't think I made any change since I committed the Hindi phones file. But I can revert those commits.

**Comment by ajmalanoski** [comment]
Okay, I think it should be good now

**Comment by kylebgorman** [comment]
Yep, LGTM, thanks. 

Those unrelated changes sometimes end up in my PRs too. Not sure what that's about.

**Pull request merged**
