### PR TITLE
[cbn] Configuration and initial scrape of Nyahkur.

### PR DESCRIPTION
**Pull request by agutkin**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM

**Review by kylebgorman — APPROVED** [review]
LGTM

**Comment by kylebgorman** [comment]
Could you run `black -l79` on `wikipron/languagecodes.py`?

**Comment by agutkin** [comment]
I've fixed `data/src/languages.json` just now but can't push here because for some reason getting your latest merge submit in this PR screws up my branch. I now can't push or pull anything.

**Comment by kylebgorman** [comment]
I'm just going to submit over the top of this and fix manually after the
fact.

**Pull request merged**
