### PR TITLE
Latin dialects

### PR DESCRIPTION
**Pull request by kylebgorman**
This is not working: the dialect files are identical; but am just sharing in case I have missed something.

### CODE REVIEW

**Comment by lfashby** [comment]
Do you mean that the you scraped Latin after adding these dialects to `languages.json` and the contents of the TSVs for the different dialects are all the same?

**Comment by kylebgorman** [comment]
Sorry, this is a terribly non-descript PR!

Yes, when I run with a (truncated for speed) `languages.json` the Ecclesiastical and Classical files are unexpectedly identical and both contain the prons labeled "Ecclesiastical" and "Classical", respectively. [Sample word with both of those dialects here](https://en.wiktionary.org/wiki/eruptio#Latin).

**Comment by kylebgorman** [comment]
Also a bunch of unrelated changes have ended up in this PR...I have too many PRs at once. But the relevant one is to `languages.json`.

**Comment by lfashby** [comment]
I think when we added the Latin extraction function (and our other extraction functions that build their own pron selectors and don't rely on `_PRON_XPATH_SELECTOR_TEMPLATE` from `config.py`) we did not consider adding dialect support.

**Comment by kylebgorman** [comment]
Okay, so if there's a language customization in `extract`, what exactly happens to the dialect specifications? Are they completely ignored, or have to be added to the language customization, or something else?

**Comment by lfashby** [comment]
As far as I can tell, languages that do not interact with `extract_word_pron_default` (and in particular `_yield_phn` and its use of `config.pron_xpath_selector` ) in `extract/default.py` do not have any dialect support - meaning all languages for which we have extraction functions just ignore dialects.

**Comment by kylebgorman** [comment]
At the very least we should document (or log loudly?) this.

And while it's not super important not sure how useful the Latin data is
without dialect specifications.

I feel like I'm out of my depth with figuring out how that works given how
elaborate the Latin extraction function is.

**Comment by lfashby** [comment]
I created an issue to track this.

**Comment by jacksonllee** [comment]
Lucas is correct that languages which require a non-default extraction treatment ignore the dialect labels unless they are specifically used in the respective extraction function. We should figure out how the extraction module for Latin can make use of `config.pron_xpath_selector` somehow (as the Japanese one does, as Lucas has pointed out). If I'm not mistaken, it would be a matter of combining the Latin-specific `pron_xpath_selector` [here](https://github.com/kylebgorman/wikipron/blob/2b36c9c3f971bb390c197d2581aa536abb751282/wikipron/extract/lat.py#L114-L115) with `config.pron_xpath_selector` that has the dialect info.

**Comment by kylebgorman** [comment]
This is quite out of date but ongoing work is happening on #143.

**Pull request closed without merging**
