### PR TITLE
Updates `data/phones/README.md` with instructions to re-scrape

### LINKED ISSUE #279: Python file to filter TSV data
We've added `list_phones.py` to facilitate the process of making phone lists. Would it make sense to add another script for filtering a language's TSV data based on its .phones file, in order to further facilitate (and standardize) the process?

### PR DESCRIPTION
**Pull request by ajmalanoski**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

Closes #279.

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM. Suggestion: in step 4 mention this may take a while, or chain steps 4-5 together 

```bash
./scrape.py --restriction=yourlang && ./postprocess && ./generate_summary.py
```

and mention that the step may take a while.

**Comment by ajmalanoski** [comment]
Sure, that makes sense to me. I'll make the edits.

**Comment by ajmalanoski** [comment]
Okay, I made the edits. Does it look good to you @kylebgorman ?

**Review by kylebgorman — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
