### PR TITLE
adds data files from directory `unimorph_data`

### PR DESCRIPTION
**Pull request by reubenraff**
git had an error saying the finnish data files are too large to append to this commit. Should I divide them into 2 files each ?

### CODE REVIEW

**Review by kylebgorman — COMMENTED** [review]
1. It's not my intention that we check in those data files, ever, since as you see, they're quite large.  Can you remove them from the PR? The user who needs them can just run the script.
2. It looks to me like you didn't check in changes to `unimorph_languages.json`, which is the most important part here. Can you include those?
3. It looks like your `get_unimorph_data.py` replicates the functionality of  `grab_unimorph_data.py` added in #369. Can you remove yours, and if it has any additional features, integrate its functionality into the existing program?

**Comment by kylebgorman** [comment]
I see the `black` test is failing. You can fix that just by reflowing the code (running `black -l79 *.py` in the morphology directory), probably.

**Comment by reubenraff** [comment]
> I see the `black` test is failing. You can fix that just by reflowing the code (running `black -l79 *.py` in the morphology directory), probably.

sgtm

**Comment by kylebgorman** [comment]
Would you like me to close this since you're working on #372, I assume as a replacement?

**Comment by kylebgorman** [comment]
Closing from inactivity; happy to discuss whether we actually want to check these files in at some point.

**Pull request closed without merging**
