### PR TITLE
Moves Latin phonelist to Classical Latin.

### LINKED ISSUE #325: Latin phones list not functional
[`data/phones/lat_phonemic.phones`](https://github.com/kylebgorman/wikipron/blob/master/data/phones/lat_phonemic.phones) needs to be split into three separate lists (`lat_clas_phonemic.phones`, `lat_vulg_phonemic.phones`, etc.) in accordance with its dialects in order to be used by `src/scrape.py`.

I'd imagine this is low-priority and perhaps this list was originally just added as a demonstration(?) but it currently doesn't do anything.

### PR DESCRIPTION
**Pull request by kylebgorman**
Also undertook a light reorg.

Closes #325

- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Two notes:

1. Not rerunning this (takes a while, but the list hasn't changed).
2. I could do the other dialects but I can do that later...this was originally just for Classical.

**Review by lfashby — APPROVED** [review]
Thanks for this.

**Comment by lfashby** [comment]
I should probably add a `data`-side test to check these things.

**Comment by kylebgorman** [comment]
Not bad idea.

**Pull request merged**
