### PR TITLE
Remove "require_dialect_label"

### LINKED ISSUE #75: Remove the "require dialect label" option
From https://github.com/kylebgorman/wikipron/issues/66#issuecomment-544214656 and subsequent discussion, we should remove the "require dialect label" option. We would lose the ability to do the following, neither of which I think is practically useful now:
* ~One wants only entries with some dialect label, but doesn't care which dialects~ (edit: I lied -- this is not possible, because when "require dialect label" is used, "dialect" must also be specified: https://github.com/kylebgorman/wikipron/blob/abecf0341268a9426e489226599ae8881c02aaf3/wikipron/config.py#L198-L202)
* One wants a particular set of dialects (by specifying the "dialect" option) but doesn't want entries that lack a dialect label -- this seems strange, as entries without a dialect label (should) mean the pronunciation applies to all (or most major) dialects.

### PR DESCRIPTION
**Pull request by jacksonllee**
Resolves #75

### CODE REVIEW

**Comment by jacksonllee** [comment]
@lfashby I see you have #76 on deck with "require_dialect_label" used, and hence I thought I should put this PR up to remove this option to help simplify your PR a little bit.

**Comment by lfashby** [comment]
Thank you. Removing the "require_dialect_label" references in my code should be easy. Perhaps I should have given you some warning before I submitted my PR though.

**Comment by jacksonllee** [comment]
No worries. Removing an option is a breaking change, and so we should probably have a separate PR like this for good software engineering practice. It's good to have your PR focus on the big scrape config work.

Tagging you for review here as well, in case you beat Kyle to it. :-)

**Comment by kylebgorman** [comment]
Implementation looks good!

I had a slightly different interpretation of how things would be interpreted after the flag was removed: I thought it was going to say that if a dialect string is specified then we only sample forms that match the string (and if not specified we sample all forms). I now realize that's not what you said ('One wants a particular set of dialects (by specifying the "dialect" option) but doesn't want entries that lack a dialect label -- this seems strange, as entries without a dialect label (should) mean the pronunciation applies to all (or most major) dialects.') But I'm willing to assume that this is fine.

**Comment by jacksonllee** [comment]
> I thought it was going to say that if a dialect string is specified then we only sample forms that match the string

In a way, I think this was the impetus of adding the "require_dialect_label" in the first place. :-) Since all our work is versioned, we could always revisit and possibly bring back this behavior in the future.

**Pull request merged**
