### PR TITLE
[ger] Adds German Phone list, filtered TSV file

### LINKED ISSUE #285: [ger] Create .phones list for German
As captioned

### PR DESCRIPTION
**Pull request by yeonju123**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.
Closes #285

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM but there's an issue with the tests...checking now.

**Comment by kylebgorman** [comment]
```AssertionError: Number of entries in ger_phonetic.tsv does not match number of entries in data/languages_summary.tsv.
assert 10955 == 10722
  +10955
  -10722
```

So you just need to run `./postprocess && ./generate_summary.py` again, I think, then commit and push all the affected files. (`git status` will tell you what files have pending changes.)

**Comment by yeonju123** [comment]
Got it!

**Comment by yeonju123** [comment]
Which test did you run?

**Comment by kylebgorman** [comment]
`tests/test_data/test_summary.py`. It runs automatically after every PR (or commit to a previously submitted PR):

Screenshot 2021-01-08 at 2 51 19 PM

I think you should be able to see the result if you look above where it currently says "some checks were not successful"...

**Comment by yeonju123** [comment]
Yes :) thank you!

**Review by kylebgorman — APPROVED** [review]
LGTM thanks Yeonju!

**Pull request merged**
