### PR TITLE
[kir] Split Kyrgyz into Cyrillic and Arabic scripts.

### PR DESCRIPTION
**Pull request by agutkin**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

### CODE REVIEW

**Review by kylebgorman — APPROVED** [review]
LGTM

**Comment by kylebgorman** [comment]
Do you want to rerun the scrape for these languages first?

**Comment by agutkin** [comment]
> Do you want to rerun the scrape for these languages first?

No. I've done already.

**Comment by kylebgorman** [comment]
Okay, but do you need to check in the TSV files? Does this not result in any changes to the data?

**Comment by agutkin** [comment]
> Okay, but do you need to check in the TSV files? Does this not result in any changes to the data?

There are no changes to the data - Kyrgiz phonemic and phonetic subsets are both under 100 entries.

**Comment by kylebgorman** [comment]
Ah, thanks for clarification. Merging now.

**Pull request merged**
