### PR TITLE
Rename "whitelist"

### LINKED ISSUE #206: Rename "whitelist"
Reason should be obvious. I would suggest:

* delete `whitelist.py`; we don't need it anymore
* rename the file extension `.phones`
* rename the subdirectory `phones`

### PR DESCRIPTION
**Pull request by jacksonllee**
Resolves #206

### CODE REVIEW

**Comment by jacksonllee** [comment]
@kylebgorman @lfashby Is there a way we could check that these changes haven't broken anything without triggering the "big scrape" process?

**Comment by kylebgorman** [comment]
You could run the actual scrape (`src/./scrape.py`) through Armenian (which will at most take a few hours) and confirm there are no obvious regressions, then revert.

**Review by kylebgorman — APPROVED** [review]
LGTM

**Comment by lfashby** [comment]
My only suggestion would be to run a partial big scrape and then just manually compare the data. It would be nice if we had a way of testing some of these things on the `data` side of WikiPron.

**Pull request merged**
