### PR TITLE
[ita] Adds phoneme list, filtered phonemic TSV file

### LINKED ISSUE #260: [ita] Create .phones list for Italian
As captioned.

### PR DESCRIPTION
**Pull request by ajmalanoski**
- [x] Updated `Unreleased` in `CHANGELOG.md` to reflect the changes in code or data.

Closes #260.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Thanks for this.

1. The tests are failing because you didn't regenerate the summary. See instructions in `data/src` for that. I think you just want to do `./postproccess && ./generate_summary.py` and then re-add and re-commit the affected files.
2. Please add "Closes #260" to the PR description. GitHub parses the CL description looking for things like that and will automatically close the bug and link it to this PR when the PR is merged.

**Comment by ajmalanoski** [comment]
Oops, I accidentally skipped that step. The updated versions of `data/README.md` and `data/language_summary.tsv` should be included now. I also edited the pull request with the issue number, as requested. Should I also modify my entry in the changelog to include the issue number as well as the pull request number?

**Review by kylebgorman — APPROVED** [review]
LGTM.

**Comment by kylebgorman** [comment]
> Should I also modify my entry in the changelog to include the issue number as well as the pull request number?

Yes, please. Other than that, it's good to go.

**Comment by ajmalanoski** [comment]
Okay, it should be taken care of.

**Review by kylebgorman — APPROVED** [review]
LGTM

**Pull request merged**
